excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://pentstr.github.io
title: PENtstR
tagline: -- The PEN is mightier than the Cyword --
description: Wow! Just Wow ᕦ(ò_ó*)ᕤ
paginate: 8
